-- Additional products for comprehensive testing of order, search and filtering features
INSERT INTO products (name, description, price, stock_quantity, metadata) VALUES

-- Tops
('Graphic Print T-Shirt', 'Relaxed-fit cotton t-shirt with bold graphic print on the front. Streetwear style.', 25.99, 80, '{"category": "tops", "color": "white", "season": ["spring", "summer"], "style": "streetwear", "material": "cotton", "gender": "unisex", "sizes_available": ["XS", "S", "M", "L", "XL", "XXL"]}'),
('Black Polo Shirt', 'Classic short-sleeve polo shirt in black with ribbed collar. Smart casual everyday wear.', 38.00, 55, '{"category": "tops", "color": "black", "season": ["spring", "summer"], "style": "smart-casual", "material": "pique-cotton", "gender": "male", "sizes_available": ["S", "M", "L", "XL", "XXL"]}'),
('Oversized Hoodie', 'Ultra-soft fleece oversized hoodie with kangaroo pocket. Perfect for lounging.', 59.99, 45, '{"category": "tops", "color": "grey", "season": ["autumn", "winter"], "style": "casual", "material": "fleece", "gender": "unisex", "sizes_available": ["S", "M", "L", "XL", "XXL"]}'),
('Linen Button-Up Shirt', 'Breathable linen shirt with relaxed fit and roll-up sleeves. Ideal for warm weather.', 52.00, 35, '{"category": "tops", "color": "beige", "season": ["spring", "summer"], "style": "smart-casual", "material": "linen", "gender": "male", "sizes_available": ["S", "M", "L", "XL"]}'),
('Ribbed Crop Top', 'Form-fitting ribbed crop top in black. Versatile layering piece.', 22.99, 60, '{"category": "tops", "color": "black", "season": ["spring", "summer", "autumn"], "style": "casual", "material": "cotton-rib", "gender": "female", "sizes_available": ["XS", "S", "M", "L"]}'),
('Turtleneck Sweater', 'Soft merino wool turtleneck sweater in cream. Classic winter essential.', 72.00, 28, '{"category": "tops", "color": "cream", "season": ["autumn", "winter"], "style": "smart-casual", "material": "merino-wool", "gender": "unisex", "sizes_available": ["XS", "S", "M", "L", "XL"]}'),

-- Bottoms
('High-Waist Mini Skirt', 'Trendy high-waist mini skirt in black faux leather. Evening and party wear.', 44.99, 32, '{"category": "bottoms", "color": "black", "season": ["spring", "summer", "autumn"], "style": "streetwear", "material": "faux-leather", "gender": "female", "sizes_available": ["XS", "S", "M", "L"]}'),
('Pleated Midi Skirt', 'Flowy pleated satin midi skirt in blush pink. Elegant and feminine.', 64.00, 25, '{"category": "bottoms", "color": "pink", "season": ["spring", "summer"], "style": "formal", "material": "satin", "gender": "female", "sizes_available": ["XS", "S", "M", "L", "XL"]}'),
('Denim Shorts', 'Classic blue denim shorts with frayed hem. Summer staple.', 35.00, 50, '{"category": "bottoms", "color": "blue", "season": ["summer"], "style": "casual", "material": "denim", "gender": "unisex", "sizes_available": ["XS", "S", "M", "L", "XL"]}'),
('Jogger Pants', 'Comfortable grey jogger pants with elastic waist and tapered leg. Athleisure essential.', 48.00, 40, '{"category": "bottoms", "color": "grey", "season": ["spring", "summer", "autumn", "winter"], "style": "casual", "material": "cotton-blend", "gender": "unisex", "sizes_available": ["XS", "S", "M", "L", "XL"]}'),
('Wide-Leg Linen Trousers', 'Relaxed wide-leg trousers in white linen. Sophisticated summer look.', 68.00, 22, '{"category": "bottoms", "color": "white", "season": ["spring", "summer"], "style": "smart-casual", "material": "linen", "gender": "female", "sizes_available": ["XS", "S", "M", "L"]}'),

-- Dresses
('Little Black Dress', 'Timeless sleeveless fit-and-flare little black dress. Perfect for any occasion.', 85.00, 30, '{"category": "dresses", "color": "black", "season": ["spring", "summer", "autumn"], "style": "formal", "material": "crepe", "gender": "female", "sizes_available": ["XS", "S", "M", "L", "XL"]}'),
('Boho Maxi Dress', 'Flowy bohemian maxi dress with floral embroidery and tiered skirt.', 78.00, 20, '{"category": "dresses", "color": "multicolor", "season": ["spring", "summer"], "style": "casual", "material": "cotton", "gender": "female", "sizes_available": ["XS", "S", "M", "L"]}'),
('Knit Mini Dress', 'Cozy ribbed knit mini dress in camel. Autumn/winter wardrobe essential.', 66.00, 25, '{"category": "dresses", "color": "camel", "season": ["autumn", "winter"], "style": "casual", "material": "knit-blend", "gender": "female", "sizes_available": ["XS", "S", "M", "L"]}'),

-- Shoes
('Strappy Heeled Sandals', 'Elegant strappy heeled sandals in nude. Elevate any outfit.', 95.00, 18, '{"category": "shoes", "color": "nude", "season": ["spring", "summer"], "style": "formal", "material": "synthetic-leather", "gender": "female", "sizes_available": ["35", "36", "37", "38", "39", "40"]}'),
('Leather Loafers', 'Classic penny loafers in tan leather. Smart casual footwear staple.', 110.00, 20, '{"category": "shoes", "color": "tan", "season": ["spring", "summer", "autumn"], "style": "smart-casual", "material": "leather", "gender": "unisex", "sizes_available": ["38", "39", "40", "41", "42", "43", "44"]}'),
('Running Sneakers', 'Lightweight performance running sneakers with cushioned sole and breathable mesh.', 88.00, 38, '{"category": "shoes", "color": "multicolor", "season": ["spring", "summer", "autumn"], "style": "sporty", "material": "mesh", "gender": "unisex", "sizes_available": ["37", "38", "39", "40", "41", "42", "43", "44"]}'),
('Ankle Boots', 'Sleek black ankle boots with block heel and side zip. Versatile all-season style.', 118.00, 22, '{"category": "shoes", "color": "black", "season": ["spring", "autumn", "winter"], "style": "smart-casual", "material": "leather", "gender": "female", "sizes_available": ["35", "36", "37", "38", "39", "40"]}'),
('Canvas Slip-On Sneakers', 'Easy-wear canvas slip-on sneakers in navy. Laid-back everyday shoe.', 39.99, 55, '{"category": "shoes", "color": "navy", "season": ["spring", "summer"], "style": "casual", "material": "canvas", "gender": "unisex", "sizes_available": ["37", "38", "39", "40", "41", "42", "43"]}'),

-- Outerwear
('Leather Biker Jacket', 'Edgy black moto leather jacket with asymmetric zipper and quilted panels.', 189.99, 12, '{"category": "outerwear", "color": "black", "season": ["spring", "autumn"], "style": "streetwear", "material": "leather", "gender": "unisex", "sizes_available": ["XS", "S", "M", "L", "XL"]}'),
('Puffer Winter Jacket', 'Warm navy puffer jacket with down fill and detachable hood. Built for cold weather.', 145.00, 20, '{"category": "outerwear", "color": "navy", "season": ["winter"], "style": "casual", "material": "nylon-down", "gender": "unisex", "sizes_available": ["XS", "S", "M", "L", "XL", "XXL"]}'),
('Windbreaker Jacket', 'Lightweight olive windbreaker with packable design. Great for outdoor activities.', 76.00, 30, '{"category": "outerwear", "color": "olive", "season": ["spring", "autumn"], "style": "casual", "material": "nylon", "gender": "unisex", "sizes_available": ["S", "M", "L", "XL"]}'),

-- Accessories
('Canvas Tote Bag', 'Minimalist large canvas tote bag in natural white. Eco-friendly everyday bag.', 28.00, 70, '{"category": "accessories", "color": "white", "season": ["spring", "summer", "autumn", "winter"], "style": "casual", "material": "canvas", "gender": "unisex", "sizes_available": ["one-size"]}'),
('Knit Beanie', 'Warm ribbed knit beanie in charcoal. Winter essential accessory.', 18.99, 65, '{"category": "accessories", "color": "charcoal", "season": ["autumn", "winter"], "style": "casual", "material": "acrylic-knit", "gender": "unisex", "sizes_available": ["one-size"]}'),
('Sunglasses Classic Wayfarer', 'Iconic black wayfarer sunglasses with UV400 protection. Summer essential.', 32.00, 50, '{"category": "accessories", "color": "black", "season": ["spring", "summer"], "style": "casual", "material": "acetate", "gender": "unisex", "sizes_available": ["one-size"]}'),
('Leather Crossbody Bag', 'Compact tan leather crossbody bag with adjustable strap. Stylish and functional.', 89.99, 18, '{"category": "accessories", "color": "tan", "season": ["spring", "summer", "autumn", "winter"], "style": "smart-casual", "material": "leather", "gender": "female", "sizes_available": ["one-size"]}'),
('Silver Chain Necklace', 'Delicate layered silver chain necklace, adjustable length. Minimalist jewelry.', 24.99, 80, '{"category": "accessories", "color": "silver", "season": ["spring", "summer", "autumn", "winter"], "style": "casual", "material": "925-silver", "gender": "female", "sizes_available": ["one-size"]}'),

-- Sportswear
('Yoga Leggings', 'High-waist compression yoga leggings in black with side pocket. 4-way stretch fabric.', 54.99, 45, '{"category": "sportswear", "color": "black", "season": ["spring", "summer", "autumn", "winter"], "style": "sporty", "material": "spandex-nylon", "gender": "female", "sizes_available": ["XS", "S", "M", "L", "XL"]}'),
('Sports Bra', 'Medium-support sports bra in dusty rose with racerback design. Comfortable activewear.', 36.00, 50, '{"category": "sportswear", "color": "pink", "season": ["spring", "summer", "autumn", "winter"], "style": "sporty", "material": "spandex-polyester", "gender": "female", "sizes_available": ["XS", "S", "M", "L"]}'),
('Athletic Shorts', 'Lightweight 5-inch athletic running shorts in black with inner liner and back pocket.', 32.00, 55, '{"category": "sportswear", "color": "black", "season": ["spring", "summer"], "style": "sporty", "material": "polyester", "gender": "male", "sizes_available": ["S", "M", "L", "XL", "XXL"]}'),
('Zip-Up Track Jacket', 'Classic zip-up track jacket in white with contrast black stripes. Sporty retro look.', 65.00, 28, '{"category": "sportswear", "color": "white", "season": ["spring", "autumn"], "style": "sporty", "material": "polyester-tricot", "gender": "unisex", "sizes_available": ["XS", "S", "M", "L", "XL"]}');
