-- Users (password: demo123, BCrypt hash)
INSERT INTO users (username, password_hash, preferences) VALUES
('demo_user', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '{"size": "M", "favorite_color": "black", "style": "minimal"}'),
('fashion_lover', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '{"size": "L", "favorite_color": "navy", "style": "smart-casual"}');

-- Products (16 fashion items matching the AI mock backend seed data)
INSERT INTO products (name, description, price, stock_quantity, metadata) VALUES
('Classic Black Blazer', 'Tailored black blazer perfect for formal and semi-formal occasions. Slim fit with notch lapel.', 89.99, 25, '{"category": "outerwear", "color": "black", "season": ["autumn", "winter", "spring"], "style": "formal", "material": "wool-blend", "gender": "unisex", "sizes_available": ["S", "M", "L", "XL"]}'),
('White Oxford Shirt', 'Classic white oxford button-down shirt. Breathable cotton fabric, versatile for any occasion.', 45.00, 50, '{"category": "tops", "color": "white", "season": ["spring", "summer", "autumn", "winter"], "style": "formal", "material": "cotton", "gender": "unisex", "sizes_available": ["S", "M", "L", "XL", "XXL"]}'),
('Navy Chino Trousers', 'Slim-fit navy chino trousers with stretch fabric. Perfect for smart casual looks.', 55.00, 40, '{"category": "bottoms", "color": "navy", "season": ["spring", "summer", "autumn"], "style": "smart-casual", "material": "cotton-stretch", "gender": "unisex", "sizes_available": ["28", "30", "32", "34", "36"]}'),
('Black Leather Chelsea Boots', 'Premium black leather Chelsea boots with elastic side panels and pull tab.', 129.99, 20, '{"category": "shoes", "color": "black", "season": ["autumn", "winter"], "style": "formal", "material": "leather", "gender": "unisex", "sizes_available": ["39", "40", "41", "42", "43", "44"]}'),
('Casual Denim Jacket', 'Classic blue denim jacket with button closure and chest pockets.', 69.99, 30, '{"category": "outerwear", "color": "blue", "season": ["spring", "autumn"], "style": "casual", "material": "denim", "gender": "unisex", "sizes_available": ["S", "M", "L", "XL"]}'),
('Floral Summer Dress', 'Lightweight floral print midi dress with V-neckline. Perfect for summer outings.', 59.99, 35, '{"category": "dresses", "color": "multicolor", "season": ["spring", "summer"], "style": "casual", "material": "chiffon", "gender": "female", "sizes_available": ["XS", "S", "M", "L"]}'),
('Grey Wool Overcoat', 'Long grey wool overcoat with double-breasted closure. Warm and sophisticated.', 159.99, 15, '{"category": "outerwear", "color": "grey", "season": ["autumn", "winter"], "style": "formal", "material": "wool", "gender": "unisex", "sizes_available": ["S", "M", "L", "XL"]}'),
('Black Slim Fit Jeans', 'Comfortable black slim-fit jeans with stretch fabric for all-day wear.', 49.99, 60, '{"category": "bottoms", "color": "black", "season": ["spring", "summer", "autumn", "winter"], "style": "casual", "material": "denim-stretch", "gender": "unisex", "sizes_available": ["28", "30", "32", "34", "36"]}'),
('Minimalist White Sneakers', 'Clean white leather sneakers with minimal design. Versatile everyday shoes.', 79.99, 45, '{"category": "shoes", "color": "white", "season": ["spring", "summer", "autumn"], "style": "casual", "material": "leather", "gender": "unisex", "sizes_available": ["38", "39", "40", "41", "42", "43", "44"]}'),
('Striped Knit Sweater', 'Cozy striped knit sweater in navy and cream. Relaxed fit for layering.', 54.99, 30, '{"category": "tops", "color": "navy", "season": ["autumn", "winter"], "style": "casual", "material": "knit-wool", "gender": "unisex", "sizes_available": ["S", "M", "L", "XL"]}'),
('Beige Trench Coat', 'Classic beige trench coat with belt and double-breasted front. Timeless style.', 139.99, 18, '{"category": "outerwear", "color": "beige", "season": ["spring", "autumn"], "style": "smart-casual", "material": "cotton-gabardine", "gender": "unisex", "sizes_available": ["S", "M", "L", "XL"]}'),
('Black Formal Trousers', 'Classic black formal trousers with pressed crease. Perfect for office and events.', 65.00, 35, '{"category": "bottoms", "color": "black", "season": ["spring", "summer", "autumn", "winter"], "style": "formal", "material": "polyester-blend", "gender": "unisex", "sizes_available": ["28", "30", "32", "34", "36"]}'),
('Olive Cargo Pants', 'Relaxed-fit olive cargo pants with multiple pockets. Streetwear essential.', 52.00, 28, '{"category": "bottoms", "color": "olive", "season": ["spring", "summer", "autumn"], "style": "streetwear", "material": "cotton-twill", "gender": "unisex", "sizes_available": ["S", "M", "L", "XL"]}'),
('Silk Evening Blouse', 'Elegant black silk blouse with subtle sheen. Ideal for evening events.', 75.00, 22, '{"category": "tops", "color": "black", "season": ["spring", "summer", "autumn", "winter"], "style": "formal", "material": "silk", "gender": "female", "sizes_available": ["XS", "S", "M", "L"]}'),
('Brown Leather Belt', 'Premium brown leather belt with brushed silver buckle. Essential accessory.', 35.00, 50, '{"category": "accessories", "color": "brown", "season": ["spring", "summer", "autumn", "winter"], "style": "smart-casual", "material": "leather", "gender": "unisex", "sizes_available": ["S", "M", "L"]}'),
('Wool Scarf', 'Soft grey wool scarf with subtle pattern. Warm and stylish winter accessory.', 29.99, 40, '{"category": "accessories", "color": "grey", "season": ["autumn", "winter"], "style": "casual", "material": "wool", "gender": "unisex", "sizes_available": ["one-size"]}');
